In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,"\n")
print(arr.shape)

[[1 2 3]
 [4 5 6]] 

(2, 3)


In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2.dtype) # data type of elements
print(arr2.ndim) # number of dimensions
print(arr2.size) # total number of elements
print(arr2.shape) # shape of the array

int64
2
6
(2, 3)





Type Convrsion

In [9]:
arr=np.array([1.2,2.4,3.5])
arr_int=arr.astype(int)
print(arr_int)

[1 2 3]


indexing & Slicing

In [11]:
arr=np.array([10,20,30,40,50])
print(arr[2])      # Accessing element at index 2
print(arr[-1])     # Accessing last element

30
50


1D Slicing

In [12]:
print(arr[1:4])   # Slicing from index 1 to 3
print(arr[:3])    # Slicing from start to index 2
print(arr[::2])   # Slicing with step 2

[20 30 40]
[10 20 30]
[10 30 50]


2D Indexing

In [13]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[1,2])      # Accessing element at row 1, column 2
print(mat[1])      # Accessing entire row 1

6
[4 5 6]


2D Slicing


In [15]:
print(mat[:,1])  # Accessing entire column 1

[2 5 8]


Copying Array (Deep & Shallow)

In [ ]:
#shallow copy example
a=np.array([1,2,3])
b=a # b references the same array as a
b[0]=99
print(a)

[99  2  3]


In [18]:
#deep copy example
a=np.array([1,2,3])
b=a.copy() # b is a separate copy of a
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


Basic Array Operations (VECTOR POWER)

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)  # Element-wise addition
print(a-b)  # Element-wise subtraction
print(a*b)  # Element-wise multiplication
print(a/b)  # Element-wise division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar Operations

In [22]:
print(a+10)  # Adding scalar to each element
print(a*2)   # Multiplying each element by scalar

[11 12 13]
[2 4 6]


Unfus(universal functions)

In [23]:
arr=np.array([1,4,9,16,25])

print(np.sqrt(arr))        # Square root
print(np.log(arr))         # Natural logarithm
print(np.exp(arr))         # Exponential
print(np.max(arr))         # Maximum value in array
print(np.min(arr))         # Minimum value in array
print(np.mean(arr))        # Mean value
print(np.sum(arr))      # Sum of all elements
print(np.std(arr))         # Standard deviation

[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
25
1
11.0
55
8.648699324175862


Boolean Indexing

In [24]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])  # Elements greater than 25
print(arr>25)     # Boolean mask

[30 40 50]
[False False  True  True  True]


Broadcasting Rule

In [ ]:
#NumPy automatically broadcasts(exapands) smaller array during arithmetic operations depending on the shape of the arrays involved. This allows for operations between arrays of different sizes and shapes without explicit loops.

In [3]:
arr = np.array([1,2,3,4])
print(arr + 10)  # Adding scalar to each element


[11 12 13 14]


In [4]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat + 10)  # Adding scalar to each element of the matrix


[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [5]:
row=np.array([1,2,3])
print(mat + row)  # Adding row vector to each row of the matrix

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


Matrix Multiplication

In [6]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))  # Matrix multiplication

[[19 22]
 [43 50]]


In [8]:
print(A.T) # Transpose of A

[[1 3]
 [2 4]]


In [9]:
print(A @ B)  # Matrix multiplication using @ operator

[[19 22]
 [43 50]]


Random Module

In [10]:
np.random.rand(5)  # Generate 5 random numbers between 0 and 1

array([0.93343109, 0.17564023, 0.95481678, 0.63513423, 0.50643378])

In [13]:
np.random.rand(3,3)  # Generate a 3x3 array of random numbers between 0 and 1

array([[0.29518762, 0.78540384, 0.19904279],
       [0.40028274, 0.15511046, 0.15147265],
       [0.91259085, 0.7022591 , 0.41313923]])

In [22]:
np.random.randint(1,100,10)  # Generate 10 random integers between 1 and 100 (inclusive)

array([ 7, 62, 75, 10, 78,  1, 67, 92, 17, 98], dtype=int32)

Reshaping Arrays

In [27]:
arr=np.arange(10)
print(arr.reshape(2,5))  # Reshape array to 2 rows and 5 columns
# print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Axis in NumPy

In [39]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
print(np.sum(arr))  # Sum of all elements

21


In [31]:
print(np.sum(arr, axis=0))  # Sum along columns

[5 7 9]


In [40]:
print(np.sum(arr,axis=1))  # Sum along rows

[ 6 15]


Where in NumPy

In [45]:
arr=np.array([1,-2,3,-4,-5])

In [46]:
result = np.where(arr<0,0,arr)  # Replace negative values with 0
print(result)

[1 0 3 0 0]


In [47]:
arr=np.array([1,2,3,4,5])

In [49]:
result = np.where(arr%2!=0,-1,arr)  # Replace odd values with -1
print(result)

[-1  2 -1  4 -1]


In [50]:
marks=np.array([45,78,89,90,56,72,88,95,67,80])

In [53]:
status=np.where(marks>=50,1,0)  # 1 for pass, 0 for fail
print(status)

[0 1 1 1 1 1 1 1 1 1]


In [54]:
data=np.array([10,20,30,40,50])

In [61]:
mean_value=int(np.mean(data))
result=np.where(data>mean_value,mean_value,data)  # Replace values greater than mean with mean
print(result)

[10 20 30 30 30]


Applying(where) condition in 2D array

In [65]:
mat = np.array([[10,20,30],[40,50,60],[70,80,99]])

In [67]:
result=np.where(mat>=50,1,0)  # 1 for values >=50, else 0
print(result)

[[0 0 0]
 [0 1 1]
 [1 1 1]]
