In [75]:
import numpy as np

Task 1

In [76]:
#Task 1.1 Create a 1D array of cost price of 3 products and print the shape and dimension of the array.

cost_price=np.array([1500,3000,5000])
print(np.ndim(cost_price))
print(np.shape(cost_price))

1
(3,)


In [77]:
#Task 1.2 Create a 2D array of daily sales of 3 products for 4 days and print the shape and dimension of the array.

Daily_sales=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(np.shape(Daily_sales))
print(np.ndim(Daily_sales))


(3, 4)
2


Task 2

In [78]:
#Task 2.1(Grace Units): The manager decides to add 2 "bonus" units to every product's daily sale for holiday report.Add 2 to the entire daily sales array. 

Daily_sales=Daily_sales+2
print(Daily_sales)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [79]:
#Task 2.2(Revenue):Calculate the total revenue for each day.(Multiply the cost price array by the daily sales matrix.)(Observe how Numpy handles the multiplication of 1D and 2D arrays)

Revenue=np.dot(cost_price,Daily_sales)
print(Revenue)

[59000 77500 53000 75000]


In [80]:
#Task 2.3(Scaling) Use np.sqrt() on the sales data to find the square root of the sales vales for a statistical curve.

sqrt_sales=np.sqrt(Daily_sales)
print(sqrt_sales)

[[3.46410162 4.12310563 3.16227766 3.74165739]
 [2.64575131 3.         2.44948974 2.82842712]
 [2.         2.23606798 2.         2.44948974]]


Task 3

In [81]:
#Task 3.1 Access the sales for Smartwatches(Row 1) for all 4 days.

print(Daily_sales[1,:])

[7 9 6 8]


In [82]:
#Task 3.2 Access the sales for all products of the first 2 days(Monday and Tuesday).

print(Daily_sales[:2,:])

[[12 17 10 14]
 [ 7  9  6  8]]


In [83]:
#Task 3.3 Access the sales of Speakers on Thrusday using double indexing. (Row 2, Column 3)

print(Daily_sales[2,3])

6


In [84]:
#Task 3.4 Using slicing extract a 2x2 sub-array representing the sales of Headphones and Smartwatches for Monday and Tuesday. (Rows 0 and 1, Columns 0 and 1)

sub_array=Daily_sales[0:2,0:2]
print(sub_array)

[[12 17]
 [ 7  9]]


Task 4

In [85]:
#Task 4.1 Flatten the 3x4 daily sales array into a 1D array of 12 elements using the .reshape() method.

flattened_sales=Daily_sales.reshape(12)
print(flattened_sales)

[12 17 10 14  7  9  6  8  4  5  4  6]


In [86]:
#Task 4.2 Convert the sales data into 2x6 matrix.

reshaped_sales=Daily_sales.reshape(2,6)
print(reshaped_sales)

[[12 17 10 14  7  9]
 [ 6  8  4  5  4  6]]


In [87]:
#Task 4.3 Use np.linspace() to create an array of 10 equal intervals between 0 and 100 to represent "Discount Percentages".

discount_percentages=np.linspace(0,100,10)
print(discount_percentages)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


Task 5

In [88]:
#Task 5.1 Use np.random.randint to generate a 3x4 array of "Predicted Sales" for the next week with values ranging from 0 to 20.

predicted_sales=np.random.randint(0,20,(3,4))
print(predicted_sales)

[[ 9 16  1 15]
 [ 6 10  5  7]
 [11 12 12 16]]


In [89]:
#Task 5.2 Generate a random array of 5 numbers between 0 and 1 using np.random.rand()

random_numbers=np.random.rand(5)
print(random_numbers)  

[0.80621003 0.25855511 0.82498092 0.13367831 0.77164883]


In [90]:
#Task 5.3(Challenge): Use np.sum() to find: 
 # Total items sold over all 4 days.  
 # Total items sold for each product (Sum across rows).

total_items_sold=np.sum(Daily_sales)
print(total_items_sold) 

total_items_per_product=np.sum(Daily_sales,axis=1)
print(total_items_per_product)

102
[53 30 19]


Task 6

In [91]:
#Task 6.1 